---
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include = FALSE, message = FALSE, warning = FALSE}

```

## Motivation

The COVID-19 pandemic has drastically affected access to care across the United States due to such factors as diversion of medical resources and personnel, reduced access to transportation, and fear of transmission of COVID-19 in healthcare facilities. In addition to fears related to the pandemic,  public health measures in place to reduce its spread may cause an increase in mental health needs. The U.S. Census Bureau, the CDC, and four additional federal agencies have conducted the Household Pulse Survey to measure social and economic effects of the COVID-19 pandemic. Among these data are indicators of reduced access to care and depression/anxiety symptoms. 

## Initial Questions and Goal

We propose to investigate whether there exists a correlation between reduced access to care and depression/anxiety symptoms during COVID-19 using these data. We will compare reduction in access to care and mental health outcomes by age, gender, race, education and state.

## Related Work

## Data Source

Data was obtained from the Household Pulse Survey data which measures [indicators of anxiety or depression] (https://healthdata.gov/dataset/indicators-anxiety-or-depression-based-reported-frequency-symptoms-during-last-7-days) and [indicators of reduced access to care] (https://healthdata.gov/dataset/indicators-reduced-access-care-due-coronavirus-pandemic-during-last-4-weeks) during the coronavirus pandemic.

## Data Summary and Results

## Interactive Plot 1

## Interactive Plot 2

## Discussion
 