---
title: "vihar_shiny_plots.Rmd"
author: "Vihar Desu"
date: "12/02/2020"
output: html_document
---

## Load packages

```{r}

library(tidyverse)
#install.packages("shiny")
library(shiny)
#install.packages("leaflet")
library(leaflet)
#install.packages("geojsonio")
library(geojsonio)

```

## Read data

```{r}
mhealth_df =
  read_csv("./data/Indicators_of_Anxiety_or_Depression_Based_on_Reported_Frequency_of_Symptoms_During_Last_7_Days.csv") %>%
  janitor::clean_names() %>% 
  rename(mhealth_ind = indicator,
         mhealth_value = value,
         mhealth_lowci = low_ci,
         mhealth_highci =  high_ci,
         mhealth_ci = confidence_interval,
         mhealth_qrange = quartile_range)

access_df =
  read_csv("data/Indicators_of_Reduced_Access_to_Care_Due_to_the_Coronavirus_Pandemic_During_Last_4_Weeks.csv") %>% 
  janitor::clean_names() %>% 
  rename(access_ind = indicator,
         access_value = value,
         access_lowci = low_ci,
         access_highci =  high_ci,
         access_ci = confidence_interval,
         access_qrange = quartile_range,
         time_period = week,
         time_period_label = week_label)

combined_df = 
  left_join(mhealth_df, access_df, by = c("phase", "group", "state", "subgroup", "time_period", "time_period_label")) %>% 
  relocate("phase", "group", "state", "subgroup", "time_period", "time_period_label")

mhealth_date <- mhealth_df %>% 
  filter(group == "By State", mhealth_ind == "Symptoms of Anxiety Disorder or Depressive Disorder")  %>% 
  separate(time_period_label, c("first_date", "second_date"), sep = " - ") %>%
  separate(second_date, c("month", "day"), sep = " ") %>%
  mutate(year = 2020) %>%
  mutate(second_date = paste(year, month, day, sep="-") %>% ymd() %>% as.Date()) %>%
  select(mhealth_ind, state, second_date, mhealth_value, mhealth_ci)

```

## Make choropleth of mental health indicator values for each sstate

```{r}

## import .json file w/ state spatial polygons
states <- geojson_read(x = "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json", what = "sp")

class(states) 

## simplify mental health data
mhealth_test <- mhealth_df %>% filter(group == "By State", time_period == 16, mhealth_ind == "Symptoms of Anxiety Disorder or Depressive Disorder")

## make color palette
pal <- colorNumeric(
  palette = "Blues",
  domain = mhealth_test$mhealth_value)

## add state shape polygons to US map
leaflet(mhealth_test) %>% 
  addPolygons(data = states, fillOpacity = 1, color = ~pal(mhealth_test$mhealth_value), stroke = FALSE, smoothFactor = 0.2)

```
